/*Copyright (c) 2015-2016 redhound.net All Rights Reserved.
 This software is the confidential and proprietary information of redhound.net You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with redhound.net*/

package com.roverpoc.rover2;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * NclUatMessages1m generated by hbm2java
 */
@Entity
@Table(name="ncl_uat_messages_1m"
    ,schema="dbo"
)
public class NclUatMessages1m  implements java.io.Serializable
 {


private NclUatMessages1mId id;

    public NclUatMessages1m() {
    }



     @EmbeddedId

    

    @AttributeOverrides( {
        @AttributeOverride(name="marketId", column=@Column(name="MARKET_ID", precision=53) ), 
        @AttributeOverride(name="batchId", column=@Column(name="BATCH_ID", precision=53) ), 
        @AttributeOverride(name="marketAction", column=@Column(name="MARKET_ACTION") ), 
        @AttributeOverride(name="srcTradeId", column=@Column(name="SRC_TRADE_ID") ), 
        @AttributeOverride(name="srcOrderId", column=@Column(name="SRC_ORDER_ID") ), 
        @AttributeOverride(name="tradeId", column=@Column(name="TRADE_ID", precision=53) ), 
        @AttributeOverride(name="orderId", column=@Column(name="ORDER_ID", precision=53) ), 
        @AttributeOverride(name="tradeType", column=@Column(name="TRADE_TYPE") ), 
        @AttributeOverride(name="tradeStatus", column=@Column(name="TRADE_STATUS") ), 
        @AttributeOverride(name="environmentId", column=@Column(name="ENVIRONMENT_ID", precision=53) ), 
        @AttributeOverride(name="environmentCode", column=@Column(name="ENVIRONMENT_CODE") ), 
        @AttributeOverride(name="sourceId", column=@Column(name="SOURCE_ID", precision=53) ), 
        @AttributeOverride(name="sourceCode", column=@Column(name="SOURCE_CODE") ), 
        @AttributeOverride(name="srcMarket", column=@Column(name="SRC_MARKET", precision=53) ), 
        @AttributeOverride(name="srcContract", column=@Column(name="SRC_CONTRACT") ), 
        @AttributeOverride(name="srcContractType", column=@Column(name="SRC_CONTRACT_TYPE") ), 
        @AttributeOverride(name="marketCode", column=@Column(name="MARKET_CODE", precision=53) ), 
        @AttributeOverride(name="contractCode", column=@Column(name="CONTRACT_CODE") ), 
        @AttributeOverride(name="contractType", column=@Column(name="CONTRACT_TYPE") ), 
        @AttributeOverride(name="expiry", column=@Column(name="EXPIRY", length=23) ), 
        @AttributeOverride(name="subType", column=@Column(name="SUB_TYPE") ), 
        @AttributeOverride(name="strike", column=@Column(name="STRIKE", precision=53) ), 
        @AttributeOverride(name="price", column=@Column(name="PRICE", precision=53) ), 
        @AttributeOverride(name="buySell", column=@Column(name="BUY_SELL", precision=53) ), 
        @AttributeOverride(name="quantity", column=@Column(name="QUANTITY", precision=53) ), 
        @AttributeOverride(name="srcExecutingBroker", column=@Column(name="SRC_EXECUTING_BROKER") ), 
        @AttributeOverride(name="executingBroker", column=@Column(name="EXECUTING_BROKER") ), 
        @AttributeOverride(name="trader", column=@Column(name="TRADER") ), 
        @AttributeOverride(name="giveInMsg", column=@Column(name="GIVE_IN_MSG", precision=53) ), 
        @AttributeOverride(name="openClose", column=@Column(name="OPEN_CLOSE") ), 
        @AttributeOverride(name="businessDate", column=@Column(name="BUSINESS_DATE", length=23) ), 
        @AttributeOverride(name="tradeDate", column=@Column(name="TRADE_DATE", length=23) ), 
        @AttributeOverride(name="userId", column=@Column(name="USER_ID") ), 
        @AttributeOverride(name="login", column=@Column(name="LOGIN") ), 
        @AttributeOverride(name="comment", column=@Column(name="COMMENT") ), 
        @AttributeOverride(name="misc1", column=@Column(name="MISC1") ), 
        @AttributeOverride(name="misc2", column=@Column(name="MISC2") ), 
        @AttributeOverride(name="misc3", column=@Column(name="MISC3") ), 
        @AttributeOverride(name="srcCurrency", column=@Column(name="SRC_CURRENCY") ), 
        @AttributeOverride(name="currencyCode", column=@Column(name="CURRENCY_CODE") ), 
        @AttributeOverride(name="srcFirm", column=@Column(name="SRC_FIRM", precision=53) ), 
        @AttributeOverride(name="srcOffice", column=@Column(name="SRC_OFFICE") ), 
        @AttributeOverride(name="srcAccount", column=@Column(name="SRC_ACCOUNT") ), 
        @AttributeOverride(name="srcAccountType", column=@Column(name="SRC_ACCOUNT_TYPE") ), 
        @AttributeOverride(name="firm", column=@Column(name="FIRM", precision=53) ), 
        @AttributeOverride(name="office", column=@Column(name="OFFICE") ), 
        @AttributeOverride(name="account", column=@Column(name="ACCOUNT") ), 
        @AttributeOverride(name="accountType", column=@Column(name="ACCOUNT_TYPE") ), 
        @AttributeOverride(name="marketStamp", column=@Column(name="MARKET_STAMP", length=23) ), 
        @AttributeOverride(name="marketStatus", column=@Column(name="MARKET_STATUS") ), 
        @AttributeOverride(name="marketStatusDesc", column=@Column(name="MARKET_STATUS_DESC") ), 
        @AttributeOverride(name="dateTime", column=@Column(name="date_time", length=23) ), 
        @AttributeOverride(name="coreSystem", column=@Column(name="core_system", length=250) ), 
        @AttributeOverride(name="coreKey", column=@Column(name="core_key", length=250) ) } )
    public NclUatMessages1mId getId() {
        return this.id;
    }
    
    public void setId(NclUatMessages1mId id) {
        this.id = id;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof NclUatMessages1m) )
		 return false;

		 NclUatMessages1m that = ( NclUatMessages1m ) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
     }


}

