/*Copyright (c) 2015-2016 redhound.net All Rights Reserved.
 This software is the confidential and proprietary information of redhound.net You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with redhound.net*/

package com.roverpoc.rovermar01.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.math.BigDecimal;


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.roverpoc.rovermar01.*;

/**
 * Service object for domain model class ConnectGmiVennUatTotal.
 * @see com.roverpoc.rovermar01.ConnectGmiVennUatTotal
 */

public interface ConnectGmiVennUatTotalService {
   /**
	 * Creates a new connectgmivennuattotal.
	 * 
	 * @param created
	 *            The information of the created connectgmivennuattotal.
	 * @return The created connectgmivennuattotal.
	 */
	public ConnectGmiVennUatTotal create(ConnectGmiVennUatTotal created);

	/**
	 * Deletes a connectgmivennuattotal.
	 * 
	 * @param connectgmivennuattotalId
	 *            The id of the deleted connectgmivennuattotal.
	 * @return The deleted connectgmivennuattotal.
	 * @throws EntityNotFoundException
	 *             if no connectgmivennuattotal is found with the given id.
	 */
	public ConnectGmiVennUatTotal delete(BigDecimal connectgmivennuattotalId) throws EntityNotFoundException;

	/**
	 * Finds all connectgmivennuattotals.
	 * 
	 * @return A list of connectgmivennuattotals.
	 */
	public Page<ConnectGmiVennUatTotal> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<ConnectGmiVennUatTotal> findAll(Pageable pageable);
	
	/**
	 * Finds connectgmivennuattotal by id.
	 * 
	 * @param id
	 *            The id of the wanted connectgmivennuattotal.
	 * @return The found connectgmivennuattotal. If no connectgmivennuattotal is found, this method returns
	 *         null.
	 */
	public ConnectGmiVennUatTotal findById(BigDecimal id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a connectgmivennuattotal.
	 * 
	 * @param updated
	 *            The information of the updated connectgmivennuattotal.
	 * @return The updated connectgmivennuattotal.
	 * @throws EntityNotFoundException
	 *             if no connectgmivennuattotal is found with given id.
	 */
	public ConnectGmiVennUatTotal update(ConnectGmiVennUatTotal updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the connectgmivennuattotals in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the connectgmivennuattotal.
	 */

	public long countAll();


    public Page<ConnectGmiVennUatTotal> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

