/*Copyright (c) 2015-2016 redhound.net All Rights Reserved.
 This software is the confidential and proprietary information of redhound.net You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with redhound.net*/

package com.roverpoc.rovermar01;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * CollatedResults generated by hbm2java
 */
@Entity
@Table(name="`collated_results`"
)

public class CollatedResults  implements java.io.Serializable {

    private Integer id;


@Type(type="DateTime")
    private LocalDateTime dateTime;
    private Date processDate;
    private String coreSystem;
    private Integer prodTotal;
    private Integer prodDups;
    private Integer prodUnique;
    private Integer prodOnly;
    private Integer inBoth;
    private Integer uatOnly;
    private Integer uatUnique;
    private Integer uatDups;
    private Integer uatTotal;
    private Integer msgsNoDiff;
    private Integer msgsDiff;
    private Integer msgsDiffUncat;
    private Integer msgsDiffCat;
    private Integer groups;
    private Integer groupsUncat;
    private Integer groupsCat;
    private Float msgsCoverage;
    private Float groupCoverage;

    public CollatedResults() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`id`", nullable=false, precision=10)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    

    @Column(name="`date_time`")
    public LocalDateTime getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="`process_date`", length=10)
    public Date getProcessDate() {
        return this.processDate;
    }
    
    public void setProcessDate(Date processDate) {
        this.processDate = processDate;
    }

    

    @Column(name="`core_system`", length=65535)
    public String getCoreSystem() {
        return this.coreSystem;
    }
    
    public void setCoreSystem(String coreSystem) {
        this.coreSystem = coreSystem;
    }

    

    @Column(name="`prod_total`", precision=10)
    public Integer getProdTotal() {
        return this.prodTotal;
    }
    
    public void setProdTotal(Integer prodTotal) {
        this.prodTotal = prodTotal;
    }

    

    @Column(name="`prod_dups`", precision=10)
    public Integer getProdDups() {
        return this.prodDups;
    }
    
    public void setProdDups(Integer prodDups) {
        this.prodDups = prodDups;
    }

    

    @Column(name="`prod_unique`", precision=10)
    public Integer getProdUnique() {
        return this.prodUnique;
    }
    
    public void setProdUnique(Integer prodUnique) {
        this.prodUnique = prodUnique;
    }

    

    @Column(name="`prod_only`", precision=10)
    public Integer getProdOnly() {
        return this.prodOnly;
    }
    
    public void setProdOnly(Integer prodOnly) {
        this.prodOnly = prodOnly;
    }

    

    @Column(name="`in_both`", precision=10)
    public Integer getInBoth() {
        return this.inBoth;
    }
    
    public void setInBoth(Integer inBoth) {
        this.inBoth = inBoth;
    }

    

    @Column(name="`uat_only`", precision=10)
    public Integer getUatOnly() {
        return this.uatOnly;
    }
    
    public void setUatOnly(Integer uatOnly) {
        this.uatOnly = uatOnly;
    }

    

    @Column(name="`uat_unique`", precision=10)
    public Integer getUatUnique() {
        return this.uatUnique;
    }
    
    public void setUatUnique(Integer uatUnique) {
        this.uatUnique = uatUnique;
    }

    

    @Column(name="`uat_dups`", precision=10)
    public Integer getUatDups() {
        return this.uatDups;
    }
    
    public void setUatDups(Integer uatDups) {
        this.uatDups = uatDups;
    }

    

    @Column(name="`uat_total`", precision=10)
    public Integer getUatTotal() {
        return this.uatTotal;
    }
    
    public void setUatTotal(Integer uatTotal) {
        this.uatTotal = uatTotal;
    }

    

    @Column(name="`msgs_no_diff`", precision=10)
    public Integer getMsgsNoDiff() {
        return this.msgsNoDiff;
    }
    
    public void setMsgsNoDiff(Integer msgsNoDiff) {
        this.msgsNoDiff = msgsNoDiff;
    }

    

    @Column(name="`msgs_diff`", precision=10)
    public Integer getMsgsDiff() {
        return this.msgsDiff;
    }
    
    public void setMsgsDiff(Integer msgsDiff) {
        this.msgsDiff = msgsDiff;
    }

    

    @Column(name="`msgs_diff_uncat`", precision=10)
    public Integer getMsgsDiffUncat() {
        return this.msgsDiffUncat;
    }
    
    public void setMsgsDiffUncat(Integer msgsDiffUncat) {
        this.msgsDiffUncat = msgsDiffUncat;
    }

    

    @Column(name="`msgs_diff_cat`", precision=10)
    public Integer getMsgsDiffCat() {
        return this.msgsDiffCat;
    }
    
    public void setMsgsDiffCat(Integer msgsDiffCat) {
        this.msgsDiffCat = msgsDiffCat;
    }

    

    @Column(name="`groups`", precision=10)
    public Integer getGroups() {
        return this.groups;
    }
    
    public void setGroups(Integer groups) {
        this.groups = groups;
    }

    

    @Column(name="`groups_uncat`", precision=10)
    public Integer getGroupsUncat() {
        return this.groupsUncat;
    }
    
    public void setGroupsUncat(Integer groupsUncat) {
        this.groupsUncat = groupsUncat;
    }

    

    @Column(name="`groups_cat`", precision=10)
    public Integer getGroupsCat() {
        return this.groupsCat;
    }
    
    public void setGroupsCat(Integer groupsCat) {
        this.groupsCat = groupsCat;
    }

    

    @Column(name="`msgs_coverage`", precision=5)
    public Float getMsgsCoverage() {
        return this.msgsCoverage;
    }
    
    public void setMsgsCoverage(Float msgsCoverage) {
        this.msgsCoverage = msgsCoverage;
    }

    

    @Column(name="`group_coverage`", precision=5)
    public Float getGroupCoverage() {
        return this.groupCoverage;
    }
    
    public void setGroupCoverage(Float groupCoverage) {
        this.groupCoverage = groupCoverage;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof CollatedResults) )
		    return false;

		 CollatedResults that = (CollatedResults) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
    }


}

