/*Copyright (c) 2015-2016 redhound.net All Rights Reserved.
 This software is the confidential and proprietary information of redhound.net You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with redhound.net*/

package com.roverpoc.rovermar01;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * CollatedResults generated by hbm2java
 */
@Entity
@Table(name="`collated_results`"
)
public class CollatedResults  implements java.io.Serializable
 {


private Integer id;


@Type(type="DateTime")
private LocalDateTime dateTime;
private Date processDate;
private String coreSystem;
private Integer numProd;
private Integer numProdOnly;
private Integer numBoth;
private Integer numUatOnly;
private Integer numUat;
private Integer numMsgsNoDiff;
private Integer numMsgsDiff;
private Integer numMsgsDiffUncat;
private Integer numMsgsDiffCat;
private Integer numGroups;
private Integer numGroupsUncat;
private Integer numGroupsCat;
private Integer numMsgsCoverage;
private Integer numGroupCoverage;
private Integer numProdDuplicates;
private Integer numUatDuplicates;

    public CollatedResults() {
    }



     @Id @GeneratedValue(strategy=IDENTITY)

    

    @Column(name="`id`", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    

    @Column(name="`date_time`")
    public LocalDateTime getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="`process_date`", length=10)
    public Date getProcessDate() {
        return this.processDate;
    }
    
    public void setProcessDate(Date processDate) {
        this.processDate = processDate;
    }

    

    @Column(name="`core_system`", length=65535)
    public String getCoreSystem() {
        return this.coreSystem;
    }
    
    public void setCoreSystem(String coreSystem) {
        this.coreSystem = coreSystem;
    }

    

    @Column(name="`num_prod`")
    public Integer getNumProd() {
        return this.numProd;
    }
    
    public void setNumProd(Integer numProd) {
        this.numProd = numProd;
    }

    

    @Column(name="`num_prod_only`")
    public Integer getNumProdOnly() {
        return this.numProdOnly;
    }
    
    public void setNumProdOnly(Integer numProdOnly) {
        this.numProdOnly = numProdOnly;
    }

    

    @Column(name="`num_both`")
    public Integer getNumBoth() {
        return this.numBoth;
    }
    
    public void setNumBoth(Integer numBoth) {
        this.numBoth = numBoth;
    }

    

    @Column(name="`num_uat_only`")
    public Integer getNumUatOnly() {
        return this.numUatOnly;
    }
    
    public void setNumUatOnly(Integer numUatOnly) {
        this.numUatOnly = numUatOnly;
    }

    

    @Column(name="`num_uat`")
    public Integer getNumUat() {
        return this.numUat;
    }
    
    public void setNumUat(Integer numUat) {
        this.numUat = numUat;
    }

    

    @Column(name="`num_msgs_no_diff`")
    public Integer getNumMsgsNoDiff() {
        return this.numMsgsNoDiff;
    }
    
    public void setNumMsgsNoDiff(Integer numMsgsNoDiff) {
        this.numMsgsNoDiff = numMsgsNoDiff;
    }

    

    @Column(name="`num_msgs_diff`")
    public Integer getNumMsgsDiff() {
        return this.numMsgsDiff;
    }
    
    public void setNumMsgsDiff(Integer numMsgsDiff) {
        this.numMsgsDiff = numMsgsDiff;
    }

    

    @Column(name="`num_msgs_diff_uncat`")
    public Integer getNumMsgsDiffUncat() {
        return this.numMsgsDiffUncat;
    }
    
    public void setNumMsgsDiffUncat(Integer numMsgsDiffUncat) {
        this.numMsgsDiffUncat = numMsgsDiffUncat;
    }

    

    @Column(name="`num_msgs_diff_cat`")
    public Integer getNumMsgsDiffCat() {
        return this.numMsgsDiffCat;
    }
    
    public void setNumMsgsDiffCat(Integer numMsgsDiffCat) {
        this.numMsgsDiffCat = numMsgsDiffCat;
    }

    

    @Column(name="`num_groups`")
    public Integer getNumGroups() {
        return this.numGroups;
    }
    
    public void setNumGroups(Integer numGroups) {
        this.numGroups = numGroups;
    }

    

    @Column(name="`num_groups_uncat`")
    public Integer getNumGroupsUncat() {
        return this.numGroupsUncat;
    }
    
    public void setNumGroupsUncat(Integer numGroupsUncat) {
        this.numGroupsUncat = numGroupsUncat;
    }

    

    @Column(name="`num_groups_cat`")
    public Integer getNumGroupsCat() {
        return this.numGroupsCat;
    }
    
    public void setNumGroupsCat(Integer numGroupsCat) {
        this.numGroupsCat = numGroupsCat;
    }

    

    @Column(name="`num_msgs_coverage`")
    public Integer getNumMsgsCoverage() {
        return this.numMsgsCoverage;
    }
    
    public void setNumMsgsCoverage(Integer numMsgsCoverage) {
        this.numMsgsCoverage = numMsgsCoverage;
    }

    

    @Column(name="`num_group_coverage`")
    public Integer getNumGroupCoverage() {
        return this.numGroupCoverage;
    }
    
    public void setNumGroupCoverage(Integer numGroupCoverage) {
        this.numGroupCoverage = numGroupCoverage;
    }

    

    @Column(name="`num_prod_duplicates`")
    public Integer getNumProdDuplicates() {
        return this.numProdDuplicates;
    }
    
    public void setNumProdDuplicates(Integer numProdDuplicates) {
        this.numProdDuplicates = numProdDuplicates;
    }

    

    @Column(name="`num_uat_duplicates`")
    public Integer getNumUatDuplicates() {
        return this.numUatDuplicates;
    }
    
    public void setNumUatDuplicates(Integer numUatDuplicates) {
        this.numUatDuplicates = numUatDuplicates;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof CollatedResults) )
		 return false;

		 CollatedResults that = ( CollatedResults ) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
     }


}

