/*Copyright (c) 2015-2016 redhound.net All Rights Reserved.
 This software is the confidential and proprietary information of redhound.net You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with redhound.net*/

package com.roverpoc.rovermar01;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Embeddable;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * ConnectGmiDataProdViewId generated by hbm2java
 */
@Embeddable
public class ConnectGmiDataProdViewId  implements java.io.Serializable {

    private BigDecimal id;
    private Date dateTime;
    private String coreSystem;
    private String coreKey;
    private Date coreProcessDate;
    private String tradeDate;
    private String member;
    private String trader;
    private String qty;
    private String price;
    private String product;
    private String expiry;
    private String currency;
    private String buySell;
    private String productIsin;

    public ConnectGmiDataProdViewId() {
    }


    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public String getCoreSystem() {
        return this.coreSystem;
    }
    
    public void setCoreSystem(String coreSystem) {
        this.coreSystem = coreSystem;
    }
    public String getCoreKey() {
        return this.coreKey;
    }
    
    public void setCoreKey(String coreKey) {
        this.coreKey = coreKey;
    }
    public Date getCoreProcessDate() {
        return this.coreProcessDate;
    }
    
    public void setCoreProcessDate(Date coreProcessDate) {
        this.coreProcessDate = coreProcessDate;
    }
    public String getTradeDate() {
        return this.tradeDate;
    }
    
    public void setTradeDate(String tradeDate) {
        this.tradeDate = tradeDate;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public String getTrader() {
        return this.trader;
    }
    
    public void setTrader(String trader) {
        this.trader = trader;
    }
    public String getQty() {
        return this.qty;
    }
    
    public void setQty(String qty) {
        this.qty = qty;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }
    public String getExpiry() {
        return this.expiry;
    }
    
    public void setExpiry(String expiry) {
        this.expiry = expiry;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    public String getBuySell() {
        return this.buySell;
    }
    
    public void setBuySell(String buySell) {
        this.buySell = buySell;
    }
    public String getProductIsin() {
        return this.productIsin;
    }
    
    public void setProductIsin(String productIsin) {
        this.productIsin = productIsin;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof ConnectGmiDataProdViewId) )
		    return false;

		 ConnectGmiDataProdViewId that = (ConnectGmiDataProdViewId) o;

         return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) )
 && ( (this.getDateTime()==that.getDateTime()) || ( this.getDateTime()!=null && that.getDateTime()!=null && this.getDateTime().equals(that.getDateTime()) ) )
 && ( (this.getCoreSystem()==that.getCoreSystem()) || ( this.getCoreSystem()!=null && that.getCoreSystem()!=null && this.getCoreSystem().equals(that.getCoreSystem()) ) )
 && ( (this.getCoreKey()==that.getCoreKey()) || ( this.getCoreKey()!=null && that.getCoreKey()!=null && this.getCoreKey().equals(that.getCoreKey()) ) )
 && ( (this.getCoreProcessDate()==that.getCoreProcessDate()) || ( this.getCoreProcessDate()!=null && that.getCoreProcessDate()!=null && this.getCoreProcessDate().equals(that.getCoreProcessDate()) ) )
 && ( (this.getTradeDate()==that.getTradeDate()) || ( this.getTradeDate()!=null && that.getTradeDate()!=null && this.getTradeDate().equals(that.getTradeDate()) ) )
 && ( (this.getMember()==that.getMember()) || ( this.getMember()!=null && that.getMember()!=null && this.getMember().equals(that.getMember()) ) )
 && ( (this.getTrader()==that.getTrader()) || ( this.getTrader()!=null && that.getTrader()!=null && this.getTrader().equals(that.getTrader()) ) )
 && ( (this.getQty()==that.getQty()) || ( this.getQty()!=null && that.getQty()!=null && this.getQty().equals(that.getQty()) ) )
 && ( (this.getPrice()==that.getPrice()) || ( this.getPrice()!=null && that.getPrice()!=null && this.getPrice().equals(that.getPrice()) ) )
 && ( (this.getProduct()==that.getProduct()) || ( this.getProduct()!=null && that.getProduct()!=null && this.getProduct().equals(that.getProduct()) ) )
 && ( (this.getExpiry()==that.getExpiry()) || ( this.getExpiry()!=null && that.getExpiry()!=null && this.getExpiry().equals(that.getExpiry()) ) )
 && ( (this.getCurrency()==that.getCurrency()) || ( this.getCurrency()!=null && that.getCurrency()!=null && this.getCurrency().equals(that.getCurrency()) ) )
 && ( (this.getBuySell()==that.getBuySell()) || ( this.getBuySell()!=null && that.getBuySell()!=null && this.getBuySell().equals(that.getBuySell()) ) )
 && ( (this.getProductIsin()==that.getProductIsin()) || ( this.getProductIsin()!=null && that.getProductIsin()!=null && this.getProductIsin().equals(that.getProductIsin()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getDateTime() == null ? 0 : this.getDateTime().hashCode() );
         result = 37 * result + ( getCoreSystem() == null ? 0 : this.getCoreSystem().hashCode() );
         result = 37 * result + ( getCoreKey() == null ? 0 : this.getCoreKey().hashCode() );
         result = 37 * result + ( getCoreProcessDate() == null ? 0 : this.getCoreProcessDate().hashCode() );
         result = 37 * result + ( getTradeDate() == null ? 0 : this.getTradeDate().hashCode() );
         result = 37 * result + ( getMember() == null ? 0 : this.getMember().hashCode() );
         result = 37 * result + ( getTrader() == null ? 0 : this.getTrader().hashCode() );
         result = 37 * result + ( getQty() == null ? 0 : this.getQty().hashCode() );
         result = 37 * result + ( getPrice() == null ? 0 : this.getPrice().hashCode() );
         result = 37 * result + ( getProduct() == null ? 0 : this.getProduct().hashCode() );
         result = 37 * result + ( getExpiry() == null ? 0 : this.getExpiry().hashCode() );
         result = 37 * result + ( getCurrency() == null ? 0 : this.getCurrency().hashCode() );
         result = 37 * result + ( getBuySell() == null ? 0 : this.getBuySell().hashCode() );
         result = 37 * result + ( getProductIsin() == null ? 0 : this.getProductIsin().hashCode() );

         return result;
    }


}

