/*Copyright (c) 2015-2016 redhound.net All Rights Reserved.
 This software is the confidential and proprietary information of redhound.net You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with redhound.net*/

package com.roverpoc.rovermar01;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * CoreSystems generated by hbm2java
 */
@Entity
@Table(name="core_systems"
)
public class CoreSystems  implements java.io.Serializable
 {


private Integer id;


@Type(type="DateTime")
private LocalDateTime dateTime;
private String coreSystem;
private String coreSystemRoverName;
private String coreProdTable;
private String coreProdConnectivity;
private String coreUatTable;
private String coreUatConnectivity;
private String coreSystemStatus;
private String coreSystemLogging;
private String coreSystemAlert;
private String coreSystemAlertTarget;

    public CoreSystems() {
    }



     @Id @GeneratedValue(strategy=IDENTITY)

    

    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    

    @Column(name="date_time")
    public LocalDateTime getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }

    

    @Column(name="core_system", length=65535)
    public String getCoreSystem() {
        return this.coreSystem;
    }
    
    public void setCoreSystem(String coreSystem) {
        this.coreSystem = coreSystem;
    }

    

    @Column(name="core_system_rover_name", length=65535)
    public String getCoreSystemRoverName() {
        return this.coreSystemRoverName;
    }
    
    public void setCoreSystemRoverName(String coreSystemRoverName) {
        this.coreSystemRoverName = coreSystemRoverName;
    }

    

    @Column(name="core_prod_table", length=65535)
    public String getCoreProdTable() {
        return this.coreProdTable;
    }
    
    public void setCoreProdTable(String coreProdTable) {
        this.coreProdTable = coreProdTable;
    }

    

    @Column(name="core_prod_connectivity", length=65535)
    public String getCoreProdConnectivity() {
        return this.coreProdConnectivity;
    }
    
    public void setCoreProdConnectivity(String coreProdConnectivity) {
        this.coreProdConnectivity = coreProdConnectivity;
    }

    

    @Column(name="core_uat_table", length=65535)
    public String getCoreUatTable() {
        return this.coreUatTable;
    }
    
    public void setCoreUatTable(String coreUatTable) {
        this.coreUatTable = coreUatTable;
    }

    

    @Column(name="core_uat_connectivity", length=65535)
    public String getCoreUatConnectivity() {
        return this.coreUatConnectivity;
    }
    
    public void setCoreUatConnectivity(String coreUatConnectivity) {
        this.coreUatConnectivity = coreUatConnectivity;
    }

    

    @Column(name="core_system_status", length=65535)
    public String getCoreSystemStatus() {
        return this.coreSystemStatus;
    }
    
    public void setCoreSystemStatus(String coreSystemStatus) {
        this.coreSystemStatus = coreSystemStatus;
    }

    

    @Column(name="core_system_logging", length=65535)
    public String getCoreSystemLogging() {
        return this.coreSystemLogging;
    }
    
    public void setCoreSystemLogging(String coreSystemLogging) {
        this.coreSystemLogging = coreSystemLogging;
    }

    

    @Column(name="core_system_alert", length=65535)
    public String getCoreSystemAlert() {
        return this.coreSystemAlert;
    }
    
    public void setCoreSystemAlert(String coreSystemAlert) {
        this.coreSystemAlert = coreSystemAlert;
    }

    

    @Column(name="core_system_alert_target", length=65535)
    public String getCoreSystemAlertTarget() {
        return this.coreSystemAlertTarget;
    }
    
    public void setCoreSystemAlertTarget(String coreSystemAlertTarget) {
        this.coreSystemAlertTarget = coreSystemAlertTarget;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof CoreSystems) )
		 return false;

		 CoreSystems that = ( CoreSystems ) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
     }


}

