/*Copyright (c) 2015-2016 redhound.net All Rights Reserved.
 This software is the confidential and proprietary information of redhound.net You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with redhound.net*/

package com.roverpoc.rovermar01;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * FilterRules generated by hbm2java
 */
@Entity
@Table(name="filter_rules"
)
public class FilterRules  implements java.io.Serializable
 {


private Integer id;


@Type(type="DateTime")
private LocalDateTime dateTime;
private String coreSystem;
private String lsValue;
private String lsSide;
private String lsField;
private String lsString;
private String lsStart;
private String lsLength;
private String operator;
private String rsValue;
private String rsSide;
private String rsField;
private String rsString;
private String rsStart;
private String rsLength;
private String comment;
private String who;


@Type(type="DateTime")
private LocalDateTime updatedTimestamp;

    public FilterRules() {
    }



     @Id @GeneratedValue(strategy=IDENTITY)

    

    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    

    @Column(name="date_time")
    public LocalDateTime getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }

    

    @Column(name="core_system", length=65535)
    public String getCoreSystem() {
        return this.coreSystem;
    }
    
    public void setCoreSystem(String coreSystem) {
        this.coreSystem = coreSystem;
    }

    

    @Column(name="ls_value", length=65535)
    public String getLsValue() {
        return this.lsValue;
    }
    
    public void setLsValue(String lsValue) {
        this.lsValue = lsValue;
    }

    

    @Column(name="ls_side", length=65535)
    public String getLsSide() {
        return this.lsSide;
    }
    
    public void setLsSide(String lsSide) {
        this.lsSide = lsSide;
    }

    

    @Column(name="ls_field", length=65535)
    public String getLsField() {
        return this.lsField;
    }
    
    public void setLsField(String lsField) {
        this.lsField = lsField;
    }

    

    @Column(name="ls_string", length=65535)
    public String getLsString() {
        return this.lsString;
    }
    
    public void setLsString(String lsString) {
        this.lsString = lsString;
    }

    

    @Column(name="ls_start", length=65535)
    public String getLsStart() {
        return this.lsStart;
    }
    
    public void setLsStart(String lsStart) {
        this.lsStart = lsStart;
    }

    

    @Column(name="ls_length", length=65535)
    public String getLsLength() {
        return this.lsLength;
    }
    
    public void setLsLength(String lsLength) {
        this.lsLength = lsLength;
    }

    

    @Column(name="operator", length=65535)
    public String getOperator() {
        return this.operator;
    }
    
    public void setOperator(String operator) {
        this.operator = operator;
    }

    

    @Column(name="rs_value", length=65535)
    public String getRsValue() {
        return this.rsValue;
    }
    
    public void setRsValue(String rsValue) {
        this.rsValue = rsValue;
    }

    

    @Column(name="rs_side", length=65535)
    public String getRsSide() {
        return this.rsSide;
    }
    
    public void setRsSide(String rsSide) {
        this.rsSide = rsSide;
    }

    

    @Column(name="rs_field", length=65535)
    public String getRsField() {
        return this.rsField;
    }
    
    public void setRsField(String rsField) {
        this.rsField = rsField;
    }

    

    @Column(name="rs_string", length=65535)
    public String getRsString() {
        return this.rsString;
    }
    
    public void setRsString(String rsString) {
        this.rsString = rsString;
    }

    

    @Column(name="rs_start", length=65535)
    public String getRsStart() {
        return this.rsStart;
    }
    
    public void setRsStart(String rsStart) {
        this.rsStart = rsStart;
    }

    

    @Column(name="rs_length", length=65535)
    public String getRsLength() {
        return this.rsLength;
    }
    
    public void setRsLength(String rsLength) {
        this.rsLength = rsLength;
    }

    

    @Column(name="comment", length=65535)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    

    @Column(name="who", length=65535)
    public String getWho() {
        return this.who;
    }
    
    public void setWho(String who) {
        this.who = who;
    }

    

    @Column(name="updated_timestamp")
    public LocalDateTime getUpdatedTimestamp() {
        return this.updatedTimestamp;
    }
    
    public void setUpdatedTimestamp(LocalDateTime updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof FilterRules) )
		 return false;

		 FilterRules that = ( FilterRules ) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
     }


}

