/*Copyright (c) 2015-2016 redhound.net All Rights Reserved.
 This software is the confidential and proprietary information of redhound.net You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with redhound.net*/

package com.roverpoc.rovermar01;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * SysaProdMessages generated by hbm2java
 */
@Entity
@Table(name="`sysa_prod_messages`"
)
public class SysaProdMessages  implements java.io.Serializable
 {


private Integer id;


@Type(type="DateTime")
private LocalDateTime dateTime;
private String coreSystem;
private String coreKey;
private String colA;
private String colB;
private String colC;
private String colD;
private String colE;

    public SysaProdMessages() {
    }



     @Id @GeneratedValue(strategy=IDENTITY)

    

    @Column(name="`id`", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    

    @Column(name="`date_time`")
    public LocalDateTime getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }

    

    @Column(name="`core_system`", length=65535)
    public String getCoreSystem() {
        return this.coreSystem;
    }
    
    public void setCoreSystem(String coreSystem) {
        this.coreSystem = coreSystem;
    }

    

    @Column(name="`core_key`", length=65535)
    public String getCoreKey() {
        return this.coreKey;
    }
    
    public void setCoreKey(String coreKey) {
        this.coreKey = coreKey;
    }

    

    @Column(name="`ColA`", length=65535)
    public String getColA() {
        return this.colA;
    }
    
    public void setColA(String colA) {
        this.colA = colA;
    }

    

    @Column(name="`ColB`", length=65535)
    public String getColB() {
        return this.colB;
    }
    
    public void setColB(String colB) {
        this.colB = colB;
    }

    

    @Column(name="`ColC`", length=65535)
    public String getColC() {
        return this.colC;
    }
    
    public void setColC(String colC) {
        this.colC = colC;
    }

    

    @Column(name="`ColD`", length=65535)
    public String getColD() {
        return this.colD;
    }
    
    public void setColD(String colD) {
        this.colD = colD;
    }

    

    @Column(name="`ColE`", length=65535)
    public String getColE() {
        return this.colE;
    }
    
    public void setColE(String colE) {
        this.colE = colE;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof SysaProdMessages) )
		 return false;

		 SysaProdMessages that = ( SysaProdMessages ) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
     }


}

