/*Copyright (c) 2015-2016 redhound.net All Rights Reserved.
 This software is the confidential and proprietary information of redhound.net You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with redhound.net*/

package com.roverpoc.rovermar01;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * TestNcliteProdMessages generated by hbm2java
 */
@Entity
@Table(name="`TEST_NCLite_prod_messages`"
)

public class TestNcliteProdMessages  implements java.io.Serializable {

    private Integer id;


@Type(type="DateTime")
    private LocalDateTime dateTime;
    private String coreSystem;
    private String coreKey;


@Type(type="DateTime")
    private LocalDateTime coreProcessDate;
    private String marketId;
    private String batchId;
    private String marketAction;
    private String srcTradeId;
    private String srcOrderId;
    private String tradeId;
    private String orderId;
    private String tradeType;
    private String tradeStatus;
    private String environmentId;
    private String environmentCode;
    private String sourceId;
    private String sourceCode;
    private String srcMarket;
    private String srcContract;
    private String srcContractType;
    private String marketCode;
    private String contractCode;
    private String contractType;
    private String expiry;
    private String subType;
    private String strike;
    private String price;
    private String buySell;
    private String quantity;
    private String srcExecutingBroker;
    private String executingBroker;
    private String trader;
    private String giveInMsg;
    private String openClose;
    private String businessDate;
    private String tradeDate;
    private String userId;
    private String login;
    private String comment;
    private String misc1;
    private String misc2;
    private String misc3;
    private String srcCurrency;
    private String currencyCode;
    private String srcFirm;
    private String srcOffice;
    private String srcAccount;
    private String srcAccountType;
    private String firm;
    private String office;
    private String account;
    private String accountType;
    private String marketStamp;
    private String marketStatus;
    private String marketStatusDesc;

    public TestNcliteProdMessages() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`id`", nullable=false, precision=10)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    

    @Column(name="`date_time`")
    public LocalDateTime getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }

    

    @Column(name="`core_system`", length=250)
    public String getCoreSystem() {
        return this.coreSystem;
    }
    
    public void setCoreSystem(String coreSystem) {
        this.coreSystem = coreSystem;
    }

    

    @Column(name="`core_key`", length=250)
    public String getCoreKey() {
        return this.coreKey;
    }
    
    public void setCoreKey(String coreKey) {
        this.coreKey = coreKey;
    }

    

    @Column(name="`core_process_date`", length=10)
    public LocalDateTime getCoreProcessDate() {
        return this.coreProcessDate;
    }
    
    public void setCoreProcessDate(LocalDateTime coreProcessDate) {
        this.coreProcessDate = coreProcessDate;
    }

    

    @Column(name="`MARKET_ID`", length=65535)
    public String getMarketId() {
        return this.marketId;
    }
    
    public void setMarketId(String marketId) {
        this.marketId = marketId;
    }

    

    @Column(name="`BATCH_ID`", length=65535)
    public String getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(String batchId) {
        this.batchId = batchId;
    }

    

    @Column(name="`MARKET_ACTION`", length=65535)
    public String getMarketAction() {
        return this.marketAction;
    }
    
    public void setMarketAction(String marketAction) {
        this.marketAction = marketAction;
    }

    

    @Column(name="`SRC_TRADE_ID`", length=65535)
    public String getSrcTradeId() {
        return this.srcTradeId;
    }
    
    public void setSrcTradeId(String srcTradeId) {
        this.srcTradeId = srcTradeId;
    }

    

    @Column(name="`SRC_ORDER_ID`", length=65535)
    public String getSrcOrderId() {
        return this.srcOrderId;
    }
    
    public void setSrcOrderId(String srcOrderId) {
        this.srcOrderId = srcOrderId;
    }

    

    @Column(name="`TRADE_ID`", length=65535)
    public String getTradeId() {
        return this.tradeId;
    }
    
    public void setTradeId(String tradeId) {
        this.tradeId = tradeId;
    }

    

    @Column(name="`ORDER_ID`", length=65535)
    public String getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    

    @Column(name="`TRADE_TYPE`", length=65535)
    public String getTradeType() {
        return this.tradeType;
    }
    
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType;
    }

    

    @Column(name="`TRADE_STATUS`", length=65535)
    public String getTradeStatus() {
        return this.tradeStatus;
    }
    
    public void setTradeStatus(String tradeStatus) {
        this.tradeStatus = tradeStatus;
    }

    

    @Column(name="`ENVIRONMENT_ID`", length=65535)
    public String getEnvironmentId() {
        return this.environmentId;
    }
    
    public void setEnvironmentId(String environmentId) {
        this.environmentId = environmentId;
    }

    

    @Column(name="`ENVIRONMENT_CODE`", length=65535)
    public String getEnvironmentCode() {
        return this.environmentCode;
    }
    
    public void setEnvironmentCode(String environmentCode) {
        this.environmentCode = environmentCode;
    }

    

    @Column(name="`SOURCE_ID`", length=65535)
    public String getSourceId() {
        return this.sourceId;
    }
    
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId;
    }

    

    @Column(name="`SOURCE_CODE`", length=65535)
    public String getSourceCode() {
        return this.sourceCode;
    }
    
    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode;
    }

    

    @Column(name="`SRC_MARKET`", length=65535)
    public String getSrcMarket() {
        return this.srcMarket;
    }
    
    public void setSrcMarket(String srcMarket) {
        this.srcMarket = srcMarket;
    }

    

    @Column(name="`SRC_CONTRACT`", length=65535)
    public String getSrcContract() {
        return this.srcContract;
    }
    
    public void setSrcContract(String srcContract) {
        this.srcContract = srcContract;
    }

    

    @Column(name="`SRC_CONTRACT_TYPE`", length=65535)
    public String getSrcContractType() {
        return this.srcContractType;
    }
    
    public void setSrcContractType(String srcContractType) {
        this.srcContractType = srcContractType;
    }

    

    @Column(name="`MARKET_CODE`", length=65535)
    public String getMarketCode() {
        return this.marketCode;
    }
    
    public void setMarketCode(String marketCode) {
        this.marketCode = marketCode;
    }

    

    @Column(name="`CONTRACT_CODE`", length=65535)
    public String getContractCode() {
        return this.contractCode;
    }
    
    public void setContractCode(String contractCode) {
        this.contractCode = contractCode;
    }

    

    @Column(name="`CONTRACT_TYPE`", length=65535)
    public String getContractType() {
        return this.contractType;
    }
    
    public void setContractType(String contractType) {
        this.contractType = contractType;
    }

    

    @Column(name="`EXPIRY`", length=65535)
    public String getExpiry() {
        return this.expiry;
    }
    
    public void setExpiry(String expiry) {
        this.expiry = expiry;
    }

    

    @Column(name="`SUB_TYPE`", length=65535)
    public String getSubType() {
        return this.subType;
    }
    
    public void setSubType(String subType) {
        this.subType = subType;
    }

    

    @Column(name="`STRIKE`", length=65535)
    public String getStrike() {
        return this.strike;
    }
    
    public void setStrike(String strike) {
        this.strike = strike;
    }

    

    @Column(name="`PRICE`", length=65535)
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }

    

    @Column(name="`BUY_SELL`", length=65535)
    public String getBuySell() {
        return this.buySell;
    }
    
    public void setBuySell(String buySell) {
        this.buySell = buySell;
    }

    

    @Column(name="`QUANTITY`", length=65535)
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    

    @Column(name="`SRC_EXECUTING_BROKER`", length=65535)
    public String getSrcExecutingBroker() {
        return this.srcExecutingBroker;
    }
    
    public void setSrcExecutingBroker(String srcExecutingBroker) {
        this.srcExecutingBroker = srcExecutingBroker;
    }

    

    @Column(name="`EXECUTING_BROKER`", length=65535)
    public String getExecutingBroker() {
        return this.executingBroker;
    }
    
    public void setExecutingBroker(String executingBroker) {
        this.executingBroker = executingBroker;
    }

    

    @Column(name="`TRADER`", length=65535)
    public String getTrader() {
        return this.trader;
    }
    
    public void setTrader(String trader) {
        this.trader = trader;
    }

    

    @Column(name="`GIVE_IN_MSG`", length=65535)
    public String getGiveInMsg() {
        return this.giveInMsg;
    }
    
    public void setGiveInMsg(String giveInMsg) {
        this.giveInMsg = giveInMsg;
    }

    

    @Column(name="`OPEN_CLOSE`", length=65535)
    public String getOpenClose() {
        return this.openClose;
    }
    
    public void setOpenClose(String openClose) {
        this.openClose = openClose;
    }

    

    @Column(name="`BUSINESS_DATE`", length=65535)
    public String getBusinessDate() {
        return this.businessDate;
    }
    
    public void setBusinessDate(String businessDate) {
        this.businessDate = businessDate;
    }

    

    @Column(name="`TRADE_DATE`", length=65535)
    public String getTradeDate() {
        return this.tradeDate;
    }
    
    public void setTradeDate(String tradeDate) {
        this.tradeDate = tradeDate;
    }

    

    @Column(name="`USER_ID`", length=65535)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    

    @Column(name="`LOGIN`", length=65535)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    

    @Column(name="`COMMENT`", length=65535)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    

    @Column(name="`MISC1`", length=65535)
    public String getMisc1() {
        return this.misc1;
    }
    
    public void setMisc1(String misc1) {
        this.misc1 = misc1;
    }

    

    @Column(name="`MISC2`", length=65535)
    public String getMisc2() {
        return this.misc2;
    }
    
    public void setMisc2(String misc2) {
        this.misc2 = misc2;
    }

    

    @Column(name="`MISC3`", length=65535)
    public String getMisc3() {
        return this.misc3;
    }
    
    public void setMisc3(String misc3) {
        this.misc3 = misc3;
    }

    

    @Column(name="`SRC_CURRENCY`", length=65535)
    public String getSrcCurrency() {
        return this.srcCurrency;
    }
    
    public void setSrcCurrency(String srcCurrency) {
        this.srcCurrency = srcCurrency;
    }

    

    @Column(name="`CURRENCY_CODE`", length=65535)
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    

    @Column(name="`SRC_FIRM`", length=65535)
    public String getSrcFirm() {
        return this.srcFirm;
    }
    
    public void setSrcFirm(String srcFirm) {
        this.srcFirm = srcFirm;
    }

    

    @Column(name="`SRC_OFFICE`", length=65535)
    public String getSrcOffice() {
        return this.srcOffice;
    }
    
    public void setSrcOffice(String srcOffice) {
        this.srcOffice = srcOffice;
    }

    

    @Column(name="`SRC_ACCOUNT`", length=65535)
    public String getSrcAccount() {
        return this.srcAccount;
    }
    
    public void setSrcAccount(String srcAccount) {
        this.srcAccount = srcAccount;
    }

    

    @Column(name="`SRC_ACCOUNT_TYPE`", length=65535)
    public String getSrcAccountType() {
        return this.srcAccountType;
    }
    
    public void setSrcAccountType(String srcAccountType) {
        this.srcAccountType = srcAccountType;
    }

    

    @Column(name="`FIRM`", length=65535)
    public String getFirm() {
        return this.firm;
    }
    
    public void setFirm(String firm) {
        this.firm = firm;
    }

    

    @Column(name="`OFFICE`", length=65535)
    public String getOffice() {
        return this.office;
    }
    
    public void setOffice(String office) {
        this.office = office;
    }

    

    @Column(name="`ACCOUNT`", length=65535)
    public String getAccount() {
        return this.account;
    }
    
    public void setAccount(String account) {
        this.account = account;
    }

    

    @Column(name="`ACCOUNT_TYPE`", length=65535)
    public String getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    

    @Column(name="`MARKET_STAMP`", length=65535)
    public String getMarketStamp() {
        return this.marketStamp;
    }
    
    public void setMarketStamp(String marketStamp) {
        this.marketStamp = marketStamp;
    }

    

    @Column(name="`MARKET_STATUS`", length=65535)
    public String getMarketStatus() {
        return this.marketStatus;
    }
    
    public void setMarketStatus(String marketStatus) {
        this.marketStatus = marketStatus;
    }

    

    @Column(name="`MARKET_STATUS_DESC`", length=65535)
    public String getMarketStatusDesc() {
        return this.marketStatusDesc;
    }
    
    public void setMarketStatusDesc(String marketStatusDesc) {
        this.marketStatusDesc = marketStatusDesc;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof TestNcliteProdMessages) )
		    return false;

		 TestNcliteProdMessages that = (TestNcliteProdMessages) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
    }


}

